### ISSUE TITLE
1.6.0 says "Failed to start GRPC server" on startup

### ISSUE THREAD

**Issue by Pentaphon** [slowscript/warpinator-android#120] opened 2023-02-19 22:01 UTC
This is on Android 11 stock rom. Happens even after you clear data and start the app again.

![Screenshot_20230219-135903](https://user-images.githubusercontent.com/49374058/219977677-a4f597e5-79f5-4ba1-9860-236e0253d069.png)

**Comment by Pentaphon** [comment] 2023-02-20 09:58
> does it get fixed by installing a previous version (is it really related to 1.6)?

Yes, because 1.5.3 worked perfectly. I upgraded to 1.6 and it started doing that on the same phone, no settings changed. 

Why not just use an ephemeral port from now on? 

>The [Internet Assigned Numbers Authority](https://en.wikipedia.org/wiki/Internet_Assigned_Numbers_Authority) (IANA) and RFC 6335 suggests the range 49152–65535 (215 + 214 to 216 − 1) for dynamic or private ports.[[3]](https://en.wikipedia.org/wiki/Ephemeral_port#cite_note-3)[[4]](https://en.wikipedia.org/wiki/Ephemeral_port#cite_note-4)

**Comment by slowscript** [comment] 2023-02-20 22:41
Rebooting the phone didn't fix it then?

I only did a very minor change in the code that could cause that message (see [blame](https://github.com/slowscript/warpinator-android/blame/master/app/src/main/java/slowscript/warpinator/Server.java#L185)). It is however not something I can revert as the features added in 1.6 depend on it (V2 connection API). I also don't see why it would be causing any issues - it is just two internal server parameters that should behave the same on every device. I'd need to see the log to have any idea of what is going on. Please see the instructions on how to get it at the bottom of [this page](https://slowscript.xyz/warpinator-android/connection-issues/).

> Why not just use an ephemeral port by default from now on to avoid port conflicts?

All other implementations use a static port so this one does too. It rarely causes issues, basically only when the app is closed in a weird way, possibly during the update.

**Comment by Pentaphon** [comment] 2023-02-21 09:21
> Rebooting the phone didn't fix it then?

Just did a reboot and that fixed it. However, I've never seen an app that required a full reboot of the phone after an upgrade. There's clearly something else that needs to be resolved so a reboot isn't necessary. 

>I'd need to see the log to have any idea of what is going on. Please see the instructions on how to get it at the bottom of [this page](https://slowscript.xyz/warpinator-android/connection-issues/).

No chance of that any more since the problem is fixed with a reboot and I can no longer reproduce it but if I see it happen again on the next upgrade I will provide a log.

**Comment by slowscript** [comment] 2023-02-24 20:17
Closing as duplicate of #56

**Closed by slowscript** 2023-02-24 20:17 UTC
