### ISSUE TITLE
Warpinator app does not see available devices

### ISSUE THREAD

**Issue by dln949** [slowscript/warpinator-android#34] opened 2021-05-03 21:41 UTC
Version 1.1 of the android app.  

It says, "No other devices found", does not show my desktop computer (Bionic) which is on the same network.  

The Flatpak version of Warpinator on the desktop computer does see the android device, but of course cannot make a connection.  

How do I convince the android app to see the desktop computer?

**Comment by StickyDigit** [comment] 2021-05-03 21:56
Sounds like a duplicate of #23 & #30.
I think you'll be seeing this problem go away on the next release ;-)
-- 
Sent from a phone. Please excuse my brevity.

**Comment by chrisaww** [comment] 2021-05-05 15:16
Try stopping Warpinator on android and restarting it. 
I had a similar issue when first installing Warpinator on Android.
On restarting the Android instance with the computer instance running it all worked for me.

**Comment by atticus-sullivan** [comment] 2021-05-05 21:00
Not quite sure if my issue goes into the right direction, but with the `1.2` version I have the issue that the app shows `null@hostname` (I can see the ip and the ports are right) but the connection couldn't be established. And on the desktop version (installed on Arch via the AUR which installs from the git repo so this should be up to date) just shows `No other computers found`.

(The keys are set right and there is no firewall on the computer)

**Comment by astromatt42** [comment] 2021-05-06 04:24
Just a quick note for the developers. I have the same problem, restarting Warpinator on Android device and LM does not resolve this. LM can see Android, Android can't see LM.
Systems are Android 11 and LM 20.1.

**Comment by StickyDigit** [comment] 2021-05-06 08:51
@astromatt42 Be sure you're using the android client version 1.2

@atticus-sullivan Which version of Android is that? You might try force quit the app and clear the cache one time, then allow it plenty of time to complete discovery. I've found that once in a while it can take longer than expected. Also note that if the android dips out of the WiFi for even a moment you'll need to click the connection (either end) to refresh it (no restart needed).

**Comment by astromatt42** [comment] 2021-05-06 11:09
To confirm, the version I am running is 1.2. Having played around with it a bit, LM now doesn't detect the Android any more, no idea why. I am sitting next to the router and desktop by the way, so there are definitely no connection issues.
Fantastic effort though, I still haven't found any other way to easily transfer files from my Android phone to my Laptop. Once warpinator works reliably it'll be the best thing since sliced bread :).

**Comment by StickyDigit** [comment] 2021-05-06 11:40
@astromatt42 : Presumably you haven't got client isolation active on the router and can ping both ways?

If in doubt, try using the Android as a hotspot to make a quick separate test network.

**Comment by slowscript** [comment] 2021-05-06 11:59
Well... If you all are on 1.2, I'm running out of ideas what could be the issue. Maybe logs could help but so far noone has been able to provide any.

**Comment by astromatt42** [comment] 2021-05-06 12:21
Can ping both ways without any issues.
Now I'm on version three: Android sees LM, but LM doesn't see Android.
Any idea where I could find the logs?

**Comment by slowscript** [comment] 2021-05-06 12:31
For Warpinator on desktop, run it with the `-d` switch. For Warpinator on Android, you need the Android Debug Bridge (ADB). Then enable USB debugging on your phone and run `adb shell ps | grep warpinator` on the computer to get the PID of a running instance of the app (should be second column) and then run `adb logcat --pid=1234` where 1234 is the PID. This will give you the entire log of the app for when it was started until you end it (or it crashes).

**Comment by atticus-sullivan** [comment] 2021-05-06 17:50
Just wanted to try this one, but `adb logcat --pid=` got me `20211`
```
$ adb logcat --pid=20211
Unrecognized Option -
```
And in the following description I didn't found the parameter `pid` (I'm using `community/android-tools 30.0.5-1` on arch linux)

As I searched on the web I thought that `-P pid` would do something like what you want to get the log, but that got me
```
$ adb logcat -P 20211
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
```
and 
```
$ sudo adb logcat -P /20211
int logctl_get(): open '/dev/hwlog_switch' fail -1, 13. Permission denied

Note: log switch off, only log_main and log_events will have logs!
```

As you may thought, I'm not that into developing Android Apps ^^, but if you can tell me what to do, I'll try to get you the logs

**Comment by slowscript** [comment] 2021-05-06 18:59
Thanks for at least trying! I had the same issue when I attempted this on Android 5. Unfortunately it doesn't work on Android <7.
I have added an option to export the log to a file today, so you can try that when I release it.

**Comment by astromatt42** [comment] 2021-05-07 00:58
Looks like I've had more success, logs attached:
[Android_warpinator_log.txt](https://github.com/slowscript/warpinator-android/files/6438299/Android_warpinator_log.txt)
[LM_warpinator_log.txt](https://github.com/slowscript/warpinator-android/files/6438300/LM_warpinator_log.txt)

Thanks for looking into this, if there is anything useful I can do, let me know.

**Comment by astromatt42** [comment] 2021-05-19 07:36
The latest version 1.2.1 resolves all issues in my case! Many thanks for putting in the work...

**Comment by dln949** [comment] 2021-05-19 14:39
I am now on version 1.2.1 of the android app.  Sadly the Ubuntu desktop and the android device do not see each other.  Both are on the same local network, firewall ports are opened up.

**Comment by slowscript** [comment] 2021-05-19 19:06
Have you tried reinstalling and rebooting the phone? One person told me over email that this helped.

**Comment by dln949** [comment] 2021-05-19 19:29
Thank you for the response.  

Reinstalling and rebooting did not help.  

I ran this terminal command:  netstat -tulpn | grep :5353    I am not sure how to read the output, but it seems to show that both my browser and one other program are using that port.  Does that tell you anything useful?

**Comment by slowscript** [comment] 2021-05-21 20:10
@dln949 Netstat output doesn't seem very useful to me since it only shows ports on the local device. One other thing you can try (while running Warpinator) is `nc -zvu 192.168.xxx.xxx 5353` with your phone's IP which should output `Connection to 192.168.xx.xxx 5353 port [udp/mdns] succeeded!`. If it doesn't, it means that either nothing is listening on that port or it is still somehow inaccessible through your network.

Another possibility I totally forgot about and should fix asap is that when the new discovery service (added 2 weeks ago) cannot start it just fails silently and the user never finds out. It should however output the exception to a log. In 1.2.1 I made it easier to obtain it. Just go to settings, enable the appropriate switch and restart the application. The log file should be saved in `Android/data/slowscript.warpinator/files`

**Comment by dln949** [comment] 2021-05-22 03:32
Thanks.  

Output of the commmand  nc -zvu 192.168.1.82 5353:  

Connection to 192.168.1.82 5353 port [udp/mdns] succeeded!

I have attached the log file you requested to view.  
[latest.log](https://github.com/slowscript/warpinator-android/files/6525729/latest.log)

**Comment by slowscript** [comment] 2021-05-22 07:13
Thanks for the log. I see it does find a device called system1 and it attempts (unsuccessfully) to connect to it. This should show up in the UI though.

Another thing: The IP it thinks your computer has starts with 10.8.. whereas your phone's IP starts with 192.168.. Are these IPs facing the same interface or maybe is this some subnet magic I don't understand? If indeed the desktop Warpinator sends IP of an incorrect interface you will probably need to wait until they release a new version which will have an option to choose the correct one (or install it from current source)

**Comment by StickyDigit** [comment] 2021-05-22 08:48
Sounds like the laptop is on a wired net and the droid is wireless, but the AP is not bridging the LAN subnet. Maybe the AP is a router with its WAN port connected to the local wired nets. Turning off DHCP on such an AP, and connecting it to the wired net using one of the 'local' ports would stop it routing the connection and put the wired and wireless hosts in the same subnet.

Warpinator can't work in a routed setup, both machines need to be in the same subnet to see each others broadcasts.

Another thing that can scupper it even if they're on a bridged WiFi, is if the AP has client isolation turned on. If that were set in this (not bridged) example, the droid would not be able to reach other WiFi hosts, even though they might reach wired ones on the other subnet, however they still couldn't use local subnet broadcasts to reach them.

The test with nc shows the AP routed the connection to the wired subnet. The log showing warpinator finding the host on another subnet is a bit baffling.

Maybe future versions of upstream Warpinator will allow for adding routed hosts manually, but for now, discovery by broadcast means only hosts in a local broadcast domain (same subnet) can be found. Auto discovery of hosts on other nets would mean receiving broadcasts from the whole internet, which would certainly break a few things.

**Comment by dln949** [comment] 2021-05-22 16:19
Thanks for the recent responses.  I understood only about 17% of what you guys wrote, not because what you wrote was bad, but because I understand so little about networks and subnets, etc.  But.....  

It did give me an idea:  I turned off the VPN I had running on my desktop computer.  Then all worked just fine.  

Am I drawing the correct conclusion:  I cannot use Warpinator when my desktop computer is running a VPN?

**Comment by StickyDigit** [comment] 2021-05-22 17:04
VPN. Didn't think of that. Yes. It would stop Warpinator unless you managed to permit local network traffic to avoid the VPN. It's possible to set the VPN to only tunnel traffic destined for addresses outside the 'local' subnet. Have a look at "route -n" with and without the VPN, you might see the VPN route removing or overruling local routes. YMMV.
-- 
Sent from a phone. Please excuse my brevity.

**Comment by dln949** [comment] 2021-05-22 23:31
FYI, here is my VPN provider's respone:  

"During a VPN connection using Surfshark, all ports besides the one used for the connection itself are closed.

We currently do not support Port-Forwarding so transferring files using this application [Warpinator] is not possible while using Surfshark."

**Comment by StickyDigit** [comment] 2021-05-23 00:19
So if I read that right "while we obfuscate your remote, all your local are broken, is simpler for us". Fair do I guess. Simple has a cost ;)
-- 
Sent from a phone. Please excuse my brevity.

**Comment by atticus-sullivan** [comment] 2021-06-04 21:12
[latest.log](https://github.com/slowscript/warpinator-android/files/6601246/latest.log)
Now I can provide my log file as well. The problem seems to be a bit different. Seams to have something to do with the certificate. 

Should this be moved to another issue (since the problem most probably is another one)?

**Comment by slowscript** [comment] 2021-06-05 19:30
@atticus-sullivan Thanks for the update. Yes, this is a different issue so it would be better to create another one to keep it organized in here. I'm also closing this one since the author's issue was resolved. There are other duplicate (and shorter) threads still open if someone wants to discuss this further.

As for the log, it is quite short. I don't see any messages indicating the application is initializing and closing. Just that it failed to receive the certificate, which is a fairly simple step and there is not much to go wrong. You have said in a previous comment that the IP and port is right so that is not the source of the issue.

Please try getting the log with this debug version: [warpinator-debug.zip](https://github.com/slowscript/warpinator-android/files/6603100/warpinator-debug.zip) (it should produce a more verbose log, but still is signed with release keys so Android shouldn't complain when you install it over the current one). Also please close the app completely with the quit button so it flushes the log to disk.

**Closed by slowscript** 2021-06-05 19:30 UTC
