### ISSUE TITLE
5ghz band isn't working properly in warpinator

### ISSUE THREAD

**Issue by m2c4yt** [slowscript/warpinator-android#75] opened 2021-09-18 09:45 UTC
first of all , I love your work. I've been using it for casual file transfers which didn't require much speed tbh but nowadays when I'm trying to share 4k videos / movies higher speed is required.
On same hotspot , same device : warpinator is giving around 5mb/s which is even lower than regular 6 or 7mb/s in 2.4ghz band.
For reference , I've used MiXplorer. Please see the screenshots.
I can give you more info / log if required in future.
thank you for your hard work...
![20210918_153855](https://user-images.githubusercontent.com/90958431/133884592-f3c72590-a223-4207-81e5-51983a544e60.jpg)
![20210918_153902](https://user-images.githubusercontent.com/90958431/133884602-db3c408a-e187-4100-9ae5-4df86d4ee053.jpg)
![20210918_153904](https://user-images.githubusercontent.com/90958431/133884603-283f86e9-0efd-4234-ad82-4521c6e6075b.jpg)

**Comment by slowscript** [comment] 2021-09-26 19:38
Hi, sorry about the delay.

Today I finally got to diagnosing this and so far I haven't discovered any obvious bottleneck in my code. You can however expect a minor improvement soon as I am going to rewrite the file saving logic.

My current suspicion is that the slower speed (4.9 MB/s vs 6.0 MB/s on my device, 2.4 GHz WiFi, don't have 5GHz) has to do with overhead of the protocol we are using (gRPC). Unfortunately I cannot change this to not break compatibility with the Linux version but the Linux Mint guys have already implemented compression to improve speed which I will be adding soon as well.

I do not have enough devices with me right now to test this, so if you want to help out, you can try whether transferring between two PCs or a phone and a PC (both ways) is faster than just between phones. This could help identify whether the issue is really in the mobile version and I should investigate further.

**Comment by BillCipher-exe** [comment] 2022-12-16 02:34
On my Windows PC (connected via LAN to a wifi-Router) i can transfer files with 40 MB/s to a Linux PC (connected via Wifi), but to my Android phone (google Pixel 6a) in the same wifi i get only 5 MB/s.

**Comment by greg-lielens** [comment] 2023-03-07 17:56
Same here, I suspect it's not linked to 5GHz wifi (which I have) but to android or maybe warpinator protocol (although unlikely if linux-linux or linux-windows are fast). About 7 MB/s here, on a  fast android phone (snapd 8 gen 1, UFS 3.1), fast lan and fast linux box (nvme ssd). Other wifi transfer on my LAN are much much faster than that, and disks should not be responsible either....

**Comment by slowscript** [comment] 2023-04-02 15:49
Thank you for pointing me in the right direction. I now have a phone with 5 GHz WiFi and can confirm there indeed was a slowdown. Version 1.6.1 should improve transfer speed significantly. On a 5 GHz network my speed went from ~7 MB/s to ~34 MB/s, so almost 5x faster. On 2.4 GHz the improvement is about 60% (due to lower top speed). Those 34 MB/s is about the same as a regular HTTP server, so I think this issue can be closed.

**Closed by slowscript** 2023-04-02 15:49 UTC
