### ISSUE TITLE
file-name-length issue

### ISSUE THREAD

**Issue by tedfillery** [slowscript/warpinator-android#95] opened 2022-03-23 20:19 UTC
Love Warpinator, so much easier than any other network file transfer app/program I've tried. However, had a recent issue transferring files (jpg images) from linux mint una to an android phone. Perhaps the issue has already been noted. The transfer died with no explanation transferring files with typical photo-type file names such as  20150504_124940.jpg. The file name length is not a problem for either Linux or Android but the limit seems to be in Warpinator. If it is a necessary Warpinator limit some more helpful error message identifying the file-name-length restriction might be helpful.

**Comment by slowscript** [comment] 2022-03-26 19:14
How did you identify that the problem is the length of the file name? I have just transferred a file with the longest file name Nemo allows me to create (251 characters including .extension and non-ASCII diacritic) and it went just fine. I think the issue may be somewhere else.

**Closed** 2023-05-08 19:41 UTC
