### ISSUE TITLE
Mint 20.1 sees Pixel 3XL but Pixel doesn't see Mint

### ISSUE THREAD

**Issue by rbrindamour** [slowscript/warpinator-android#30] opened 2021-05-02 17:49 UTC
May 1st I installed Warpinator 1.1 on my Pixel 3 XL. When I open Warpinator on my Mint 20.1 laptop I see the phone but the phone does not see the laptop.  I've tried altering various settings with no improvement.  I use Warpinator frequently with 2 laptops running Mint 20.1 and it works well in both directions. Things I've tried
- change port number
- change Group code
- restart after each change (both laptop and phone app)
- restart phone then restart app
- restart laptop
- use port 8114 which works with a wallet app that synchronizes between laptops and phones
Nothing allows phone to see the laptops.

![Warpinator_Mint](https://user-images.githubusercontent.com/3430949/116821867-8f8b8f00-ab30-11eb-85e4-de678c0f7110.jpg)
![Warpinator_Pixel](https://user-images.githubusercontent.com/3430949/116821868-8f8b8f00-ab30-11eb-9b71-e3c8292d8a5a.jpg)

**Comment by Isolator70** [comment] 2021-05-02 18:10
In my case it is vice versa: The mobile sees the PC, but the PC doesn't see the mobile (Huawei P10, Android 9). Also using another mobile with Warpinator does not bring any working connection: The second mobile (Huawei P8 lite 2017) sees the PC and the Huawei P10, but they don't see the P8 lite. Also restarting the devices in random order does not improve the situation.
After waiting a while the list with "Available devices" on Android show a red circle with "!" (Connection failed).
If I can support in debugging (deliver more information, testing, etc) don't hesitate to ask me.

**Comment by slowscript** [comment] 2021-05-03 16:43
Duplicate of #23. I would be grateful if anyone capable of building android apps could test out the changes in jmdns branch to see if it resolved this problem.

**Closed** 2022-01-02 20:58 UTC
Labels: duplicate
