### ISSUE TITLE
Can not connect to my phone using its hotspot.

### ISSUE THREAD

**Issue by DuttaAB-dev** [slowscript/warpinator-android#58] opened 2021-06-16 15:22 UTC
I am using My phone's hotspot to connect to it with my laptop but is unable to do so. Both devices show that no device is available.

**Comment by slowscript** [comment] 2021-06-16 16:04
Did you restart the application after starting the hotspot? This is necessary but I'm working on removing this requirement. Also, does it work on any other WiFi or is this specific to the hotspot? Does it show any errors in the log?

**Comment by DuttaAB-dev** [comment] 2021-06-17 03:49
Yes, it works with my home wifi. But fails to connect or find my device when I am trying to connect to my phone by connecting to its Hotspot. I tried restarting the app as you said, and got this error message after every restart.
![Screenshot_2021-06-17-09-16-10-059_slowscript.warpinator.jpg](https://user-images.githubusercontent.com/61903332/122328309-0ba92d00-cf4d-11eb-9478-7515b74bd759.jpg)

**Comment by slowscript** [comment] 2021-06-17 12:59
Thanks! Now I know what the issue is. I'm currently working on redoing the logic that chooses network interface so expect this to be fixed soon.

**Comment by DuttaAB-dev** [comment] 2021-06-21 08:48
Cool!

**Comment by slowscript** [comment] 2021-06-24 12:09
Should be fixed in v1.3. Feel free to reopen if problems persist.

**Closed by slowscript** 2021-06-24 12:09 UTC
